# Generated by Django 5.0.3 on 2024-05-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='homeswiper',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=8),
        ),
    ]
