# Generated by Django 5.0.3 on 2024-05-29 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminap', '0002_alter_achievement_status_alter_homeswiper_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouthistory',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='aboutprinciple',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='aboutvision',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='moredoc',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'ordering': ['first_upload_date']},
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 835375, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouthistory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='aboutprinciple',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 832187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='aboutprinciple',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutprinciple',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='aboutvision',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 832187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='aboutvision',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutvision',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='aboutvision',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 839021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='gallery',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 839021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='gallery',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='moredoc',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 839021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='moredoc',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moredoc',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='news',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 839021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='news',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='notice',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 836804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='notice',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='social',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 839021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='social',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 845251, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='lastDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutprinciple',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 826985, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeswiper',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 826985, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='homeswiper',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 30, 13, 831633, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='moredoc',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8),
        ),
    ]
