# Generated by Django 5.0.3 on 2024-05-31 16:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminap', '0003_alter_abouthistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='abouthistory',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 166079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aboutprinciple',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 166079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aboutvision',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 166079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 166079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 169189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 169189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='homeswiper',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 165039, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 166079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='moredoc',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 169189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 169189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 166079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='social',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 169189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='first_upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 16, 5, 22, 169189, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MunicipalityInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminap.districtinformation')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminap.provinceinformation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='districtinformation',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminap.provinceinformation'),
        ),
    ]
